name: my first actions yaml file

on: 
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  hello: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run task
        run: echo "hello world"
        shell: bash
  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: run goodbye task
        run: echo "goodbye world"
        shell: bash


